version: '3.7'

services:
  client:
    image: lightmaze/oauthclient:latest
    ports:
        - "5003:5003"
    command: dotnet msdo.oauth.client.dll --ConfigurationFile=DockerCompose.json
    networks:
        - authnet

  AuthorizationServer:
    image: lightmaze/oauthauthserver:latest
    #The host name is used as issuer name, and must therefor match thr URL used
    hostname: http://AuthorizationServer:5001
    expose:
        - "5001"
    command: dotnet msdo.oauth.identityServer.dll 
    networks:
        - authnet

  ProtectedResourceServer:
    image: lightmaze/oauthprotectedresourceserver:latest
    expose:
        - "5002"
    command: dotnet msdo.oauth.protectedResource.dll --ConfigurationFile=DockerCompose.json
    networks:
        - authnet
networks: 
  authnet: