name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore msdo.oauth.sln
    - name: Build 
      run: dotnet build --no-restore msdo.oauth.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal msdo.oauth.sln
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Authenticate to Docker hub
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_CLIENT_SERIVCE_REPO_TOKEN }}
    - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lightmaze/oauthclient